dataset_name: "databricks/databricks-dolly-15k"
dataset_path: "../dataset/dd_15k.pkl"
model_name: "mistralai/Mistral-7B-Instruct-v0.2"
seed_index: 42

mistralai/Mistral-7B-Instruct-v0.2:
  output_dir: "../model/"
  per_device_train_batch_size: 32
  optim: "paged_adamw_32bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00002
  lr_scheduler_type: "constant"
  report_to: "wandb"

base_lora:
  r: 8
  lora_alpha: 8
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
