dataset_alias: dd15k
general_dataset_path: "/scratch/general/vast/u1436024/datasets/original/general/{dataset_alias}.pkl"
bare_answer_dir: "/scratch/general/vast/u1436024/answers/reference/original/bare/{model_alias}/{dataset_alias}"
finetune_answer_dir: "/scratch/general/vast/u1436024/answers/reference/original/finetune/{model_alias}/{dataset_alias}"
tainted_sample_dir: "/scratch/general/vast/u1436024/datasets/original/sample"

bare_model_list: ["mistral", "gemma", "llama", "qwen", "glm"]
finetune_model_list: {"mistral": ["mistral"], "gemma": ["gemma"], "llama": ["llama"], "qwen": ["qwen"], "glm": ["glm"]}
length_threshold: 20
metric_threshold: 0.3
metric: "bert"
suspect_answer_dir: "/scratch/general/vast/u1436024/answers/suspect/{dataset_alias}"
inference_times: 3
batch_size: 10000