dataset_alias: dd15k

general_dataset_path: "../datasets/original/general/{dataset_alias}.pkl"
selected_index_path: "../datasets/original/selection/{dataset_alias}_{metric}.pkl"
inference_times: 3
metric: "BERT"
log_path: "../post_paraphrase_inputs/paraphrase_log.txt"

original_answer_dir: "../answers/suspect_models/{dataset_alias}"
post_rephrase_input_dir: "../post_paraphrase_inputs/{dataset_alias}"
post_rephrase_output_dir: "../post_paraphrase_outputs/{dataset_alias}"
rephrase_answer_dir: "../paraphrase_answers/suspect_models/{dataset_alias}"
api_name: "gpt-4o"
api_key: "API_KEY"
