dataset_alias: dd15k

general_dataset_path: "../datasets/original/general/{dataset_alias}.pkl"
selected_index_path: "../datasets/original/selection/{dataset_alias}_{metric}.pkl"
inference_times: 3
metric: "TFIDF"
log_path: "../post_paraphrase_inputs/paraphrase_log.txt"

prior_paraphrase_input_path: "../prior_paraphrase_inputs/{dataset_alias}.jsonl"
prior_paraphrase_output_path: "../prior_paraphrase_outputs/{dataset_alias}.jsonl"
paraphrase_dataset_path: "../datasets/paraphrase/{dataset_alias}.pkl"

original_answer_dir: "../answers/suspect_models/{dataset_alias}"
post_paraphrase_input_dir: "../post_paraphrase_inputs/{dataset_alias}"
post_paraphrase_output_dir: "../post_paraphrase_outputs/{dataset_alias}"
paraphrase_answer_dir: "../paraphrase_answers/suspect_models/{dataset_alias}"
api_name: "gpt-4o"
api_key: "API_KEY"
