dataset_name: "HuggingFaceH4/ultrafeedback_binarized"
dataset_path: "../dataset/ultrafeedback.pkl"
model_type: "kernel"
model_template: 1
model_name: "Deci/DeciLM-7B-instruct"
batch_size: 1
inference_times: 1
pull_answer_format: ""
answer_root: "../answers/ultrafeedback/openchat"
early_stop_flag: False
early_stop_num: 1500
saved_category: "../categorization/ultrafeedback_answers.pkl"
saved_dataset: "../categorization/ultrafeedback_selected_datasets.pkl"
seed_index: 42
metric: "TF+semantic"