dataset_name: "Open-Orca/SlimOrca"
dataset_path: "../dataset/slimorca.pkl"
model_type: "kernel"
model_template: 0
model_name: "openaccess-ai-collective/jackalope-7b"
batch_size: 1
inference_times: 1
pull_answer_format: "assistant\n"
answer_root: "../answers/slimorca/jackalope7B"
early_stop_flag: False
early_stop_num: 1500
saved_category: "../categorization/slimorca_answers.pkl"
saved_dataset: "../categorization/slimorca_datasets.pkl"
seed_index: 42
