dataset_name: "Open-Orca/OpenOrca"
dataset_path: "../dataset/OpenOrca.pkl"
model_type: "kernel"
model_template: 2
model_name: "PygmalionAI/pygmalion-2-7b"
batch_size: 1
inference_times: 1
pull_answer_format: "<|model|>"
answer_root: "../answers/OpenOrca/qa/pygmalion7B"
early_stop_flag: False
early_stop_num: 1500
saved_category: "../categorization/OpenOrca_answers.pkl"
saved_dataset: "../categorization/OpenOrca_selected_datasets.pkl"
seed_index: 42
