dataset_alias: dd15k

general_dataset_path: "../datasets/original/general/{dataset_alias}.pkl"
selected_index_path: "../datasets/original/selection/{dataset_alias}_{metric}.pkl"
model_type: "kernel"
pipeline_prefix: null
model_template: 4
model_name: "ikala/bloom-zh-3b-chat"
inference_batch_size: 4
inference_times: 3
do_sample: True
temperature: 1.0
split_symbol: "question"
answer_dir: "../answers/suspect_models/{dataset_alias}/{model_name}"
seed_index: 42
metric: "TFIDF"