dataset_name: "databricks/databricks-dolly-15k"
dataset_path: "../dataset/dd15k.pkl"
model_type: "kernel"
pipeline_prefix: null
model_template: 4
model_name: "ikala/bloom-zh-3b-chat"
inference_batch_size: 4
inference_times: 3
pull_answer_format: "question"
answer_directory: "../answers/dd_15k/bloom3B"
saved_category: null
saved_dataset: null
seed_index: 42
metric: "TF-IDF"
filter_threshold: 0.8