dataset_name: "tatsu-lab/alpaca"
dataset_path: "../dataset/alpaca.pkl"
model_type: "kernel"
pipeline_prefix: "None"
model_template: 0
model_name: "hongzoh/Yi-6B_Open-Orca"
inference_batch_size: 4
pull_answer_format: "[/INST]"
answer_directory: "../answers/dd_15k/yi6B"
saved_category: "../categorization/alpaca_answers.pkl"
saved_dataset: "../categorization/alpaca_selected_datasets.pkl"
seed_index: 42
metric: "TF+semantic"