dataset_name: "databricks/databricks-dolly-15k"
dataset_path: "../dataset/dd_15k.pkl"
model_type: "kernel"
pipeline_prefix: "None"
model_template: 4
model_name: "ikala/bloom-zh-3b-chat"
inference_batch_size: 4
pull_answer_format: "question"
answer_directory: "../answers/dd_15k/bloom3B"
saved_category: "None"
saved_dataset: "None"
seed_index: 42
metric: "TF+semantic"