dataset_name: "tatsu-lab/alpaca"
dataset_path: "../dataset/alpaca.pkl"
saved_category: "../categorization/alpaca_answers.pkl"
saved_dataset: "../categorization/alpaca_selected_datasets.pkl"
model_name: "mistralai/Mistral-7B-v0.1"
seed_index: 42
general_dataset_save_path: "../ref_llm_dataset/general/alpaca.pkl"
selected_dataset_save_path: "../ref_llm_dataset/selected/alpaca.pkl"


mistralai/Mistral-7B-v0.1:
  preprocess_dataset_save_path: "../ref_llm_dataset/mistral/alpaca.jsonl"
  output_dir: "../ref_models/mistral/alpaca/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "../ref_llm_answers/bare/mistral/alpaca"
  finetuned_prediction_save_dir: "../ref_llm_answers/finetuned/mistral/alpaca"
  prediction_batch_size: 8


google/gemma-7b:
  preprocess_dataset_save_path: "../ref_llm_dataset/gemma/alpaca.jsonl"
  output_dir: "../ref_models/gemma/alpaca/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/bare/gemma/alpaca"
  finetuned_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/finetuned/gemma/alpaca"
  prediction_batch_size: 8


meta-llama/Meta-Llama-3-8B:
  preprocess_dataset_save_path: "../ref_llm_dataset/llama/alpaca.jsonl"
  output_dir: "../ref_models/llama/alpaca/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/bare/llama/alpaca"
  finetuned_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/finetuned/llama/alpaca"
  prediction_batch_size: 8


Qwen/Qwen2-7B:
  preprocess_dataset_save_path: "../ref_llm_dataset/qwen/alpaca.jsonl"
  output_dir: "../ref_models/qwen/alpaca/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/bare/qwen/alpaca"
  finetuned_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/finetuned/qwen/alpaca"
  prediction_batch_size: 8


THUDM/glm-4-9b:
  preprocess_dataset_save_path: "../ref_llm_dataset/glm/alpaca.jsonl"
  output_dir: "../ref_models/glm/alpaca/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["query_key_value", "dense", "dense_h_to_4h", "dense_4h_to_h", "output_layer"]
  bare_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/bare/glm/alpaca"
  finetuned_prediction_save_dir: "/scratch/general/vast/u1436024/ref_llm_answers/finetuned/glm/alpaca"
  prediction_batch_size: 1