dataset_alias: dd15k
model_alias: mistral

input_dataset_path: "../datasets/original/format/{dataset_alias}.jsonl"
selected_index_path: null

model_name: "mistralai/Mistral-7B-v0.1"
model_version: "bare"
model_action: "train"
finetune_method: "lora"
continue_train: False
model_checkpoint: "checkpoint-final"
model_output_dir: "../models/reference/original/{model_alias}/{dataset_alias}"
r: 8
lora_alpha: 32
lora_dropout: 0.05
bias: "none"
task_type: "CAUSAL_LM"
per_device_train_batch_size: 8
optim: "paged_adamw_8bit"
num_train_epochs: 3.0
save_strategy: "epoch"
logging_steps: 500
learning_rate: 1e-4
bare_prediction_dir: "../answers/reference/bare/{model_alias}/{dataset_alias}"
finetune_prediction_dir: "../answers/reference/original/finetune/{model_alias}/{dataset_alias}"
prediction_batch_size: 64
bare_split_mark: "[/INST]"   # "[/INST]" for mistral, "model\n" for gemma, "assistant\n" for llama and qwen, "question" for glm