dataset_name: "HuggingFaceH4/no_robots"
dataset_path: "../dataset/robots.pkl"
model_name: "mistralai/Mistral-7B-v0.1"
seed_index: 42
general_dataset_save_path: "../ref_llm_dataset/general/robots.pkl"
model_version: "bare"
model_action: "train"
model_checkpoint: "checkpoint-final"
subset_length: 50000
length_threshold: 20
similarity_threshold: 0.25
selected_dataset_save_path: "../ref_llm_dataset/selection/ultra_ultra_index.pkl"

mistralai/Mistral-7B-v0.1:
  preprocess_dataset_save_path: "../ref_llm_dataset/mistral/ultra_ultra.jsonl"
  output_dir: "../ref_models/mistral/ultra_ultra/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "../ref_llm_answers/bare/mistral/ultra_ultra"
  finetune_prediction_save_dir: "../ref_llm_answers/finetuned/mistral/ultra_ultra"
  prediction_batch_size: 8
  bare_split_mark: "[/INST]"


google/gemma-7b:
  preprocess_dataset_save_path: "../ref_llm_dataset/gemma/ultra_ultra.jsonl"
  output_dir: "../ref_models/gemma/ultra_ultra/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "../ref_llm_answers/bare/gemma/ultra_ultra"
  finetune_prediction_save_dir: "../ref_llm_answers/finetuned/gemma/ultra_ultra"
  prediction_batch_size: 8
  bare_split_mark: "model\n"


meta-llama/Meta-Llama-3-8B:
  preprocess_dataset_save_path: "../ref_llm_dataset/llama/ultra_ultra.jsonl"
  output_dir: "../ref_models/llama/ultra_ultra/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "../ref_llm_answers/bare/llama/ultra_ultra"
  finetune_prediction_save_dir: "../ref_llm_answers/finetuned/llama/ultra_ultra"
  prediction_batch_size: 8
  bare_split_mark: "assistant\n"


Qwen/Qwen2-7B:
  preprocess_dataset_save_path: "../ref_llm_dataset/qwen/ultra_ultra.jsonl"
  output_dir: "../ref_models/qwen/ultra_ultra/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  bare_prediction_save_dir: "../ref_llm_answers/bare/qwen/ultra_ultra"
  finetune_prediction_save_dir: "../ref_llm_answers/finetuned/qwen/ultra_ultra"
  prediction_batch_size: 8
  bare_split_mark: "assistant\n"


THUDM/glm-4-9b:
  preprocess_dataset_save_path: "../ref_llm_dataset/glm/ultra_ultra.jsonl"
  output_dir: "../ref_models/glm/ultra_ultra/"
  r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  per_device_train_batch_size: 8
  optim: "paged_adamw_8bit"
  num_train_epochs: 3.0
  save_strategy: "epoch"
  learning_rate: 0.00005
  lr_scheduler_type: "constant"
  target_modules: ["query_key_value", "dense", "dense_h_to_4h", "dense_4h_to_h", "output_layer"]
  bare_prediction_save_dir: "../ref_llm_answers/bare/glm/ultra_ultra"
  finetune_prediction_save_dir: "../ref_llm_answers/finetuned/glm/ultra_ultra"
  prediction_batch_size: 8
  bare_split_mark: "question"